// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTcpestats returns the embedded CollectionSpec for tcpestats.
func loadTcpestats() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpestatsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpestats: %w", err)
	}

	return spec, err
}

// loadTcpestatsObjects loads tcpestats and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//     *tcpestatsObjects
//     *tcpestatsPrograms
//     *tcpestatsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpestatsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpestats()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpestatsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpestatsSpecs struct {
	tcpestatsProgramSpecs
	tcpestatsMapSpecs
}

// tcpestatsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpestatsProgramSpecs struct {
	TcpCreateOpenreqChild *ebpf.ProgramSpec `ebpf:"tcp_create_openreq_child"`
	TcpInitSock           *ebpf.ProgramSpec `ebpf:"tcp_init_sock"`
}

// tcpestatsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpestatsMapSpecs struct {
	Entries *ebpf.MapSpec `ebpf:"entries"`
}

// tcpestatsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpestatsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpestatsObjects struct {
	tcpestatsPrograms
	tcpestatsMaps
}

func (o *tcpestatsObjects) Close() error {
	return _TcpestatsClose(
		&o.tcpestatsPrograms,
		&o.tcpestatsMaps,
	)
}

// tcpestatsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpestatsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpestatsMaps struct {
	Entries *ebpf.Map `ebpf:"entries"`
}

func (m *tcpestatsMaps) Close() error {
	return _TcpestatsClose(
		m.Entries,
	)
}

// tcpestatsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpestatsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpestatsPrograms struct {
	TcpCreateOpenreqChild *ebpf.Program `ebpf:"tcp_create_openreq_child"`
	TcpInitSock           *ebpf.Program `ebpf:"tcp_init_sock"`
}

func (p *tcpestatsPrograms) Close() error {
	return _TcpestatsClose(
		p.TcpCreateOpenreqChild,
		p.TcpInitSock,
	)
}

func _TcpestatsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed tcpestats_bpfel.o
var _TcpestatsBytes []byte
