// Code generated by "stringer -type=AppVar"; DO NOT EDIT.

package tcp_estats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[APP_TABLE_SNDMAX-0]
	_ = x[APP_TABLE_THRUOCTETSACKED-1]
	_ = x[APP_TABLE_THRUOCTETSRECEIVED-2]
	_ = x[APP_TABLE_MAXAPPWQUEUE-3]
	_ = x[APP_TABLE_MAXAPPRQUEUE-4]
}

const _AppVar_name = "APP_TABLE_SNDMAXAPP_TABLE_THRUOCTETSACKEDAPP_TABLE_THRUOCTETSRECEIVEDAPP_TABLE_MAXAPPWQUEUEAPP_TABLE_MAXAPPRQUEUE"

var _AppVar_index = [...]uint8{0, 16, 41, 69, 91, 113}

func (i AppVar) String() string {
	if i >= AppVar(len(_AppVar_index)-1) {
		return "AppVar(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AppVar_name[_AppVar_index[i]:_AppVar_index[i+1]]
}
