// Code generated by "stringer -type=ConnectionVar"; DO NOT EDIT.

package tcp_estats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CONNECTION_TABLE_ADDRESS_TYPE-0]
	_ = x[CONNECTION_TABLE_LOCAL_ADDRESS-1]
	_ = x[CONNECTION_TABLE_REMOTE_ADDRESS-2]
	_ = x[CONNECTION_TABLE_LOCAL_PORT-3]
	_ = x[CONNECTION_TABLE_REMOTE_PORT-4]
}

const _ConnectionVar_name = "CONNECTION_TABLE_ADDRESS_TYPECONNECTION_TABLE_LOCAL_ADDRESSCONNECTION_TABLE_REMOTE_ADDRESSCONNECTION_TABLE_LOCAL_PORTCONNECTION_TABLE_REMOTE_PORT"

var _ConnectionVar_index = [...]uint8{0, 29, 59, 90, 117, 145}

func (i ConnectionVar) String() string {
	if i >= ConnectionVar(len(_ConnectionVar_index)-1) {
		return "ConnectionVar(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionVar_name[_ConnectionVar_index[i]:_ConnectionVar_index[i+1]]
}
