// Code generated by "stringer -type=ExtrasVar"; DO NOT EDIT.

package tcp_estats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EXTRAS_TABLE_OTHERREDUCTIONSCV-0]
	_ = x[EXTRAS_TABLE_OTHERREDUCTIONSCM-1]
	_ = x[EXTRAS_TABLE_PRIORITY-2]
}

const _ExtrasVar_name = "EXTRAS_TABLE_OTHERREDUCTIONSCVEXTRAS_TABLE_OTHERREDUCTIONSCMEXTRAS_TABLE_PRIORITY"

var _ExtrasVar_index = [...]uint8{0, 30, 60, 81}

func (i ExtrasVar) String() string {
	if i >= ExtrasVar(len(_ExtrasVar_index)-1) {
		return "ExtrasVar(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExtrasVar_name[_ExtrasVar_index[i]:_ExtrasVar_index[i+1]]
}
