// Code generated by "stringer -type=GlobalVar"; DO NOT EDIT.

package tcp_estats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GLOBAL_TABLE_LIMSTATE-0]
	_ = x[GLOBAL_TABLE_LIMSTATE_TS-1]
	_ = x[GLOBAL_TABLE_START_TS-2]
	_ = x[GLOBAL_TABLE_CURRENT_TS-3]
	_ = x[GLOBAL_TABLE_START_TV-4]
}

const _GlobalVar_name = "GLOBAL_TABLE_LIMSTATEGLOBAL_TABLE_LIMSTATE_TSGLOBAL_TABLE_START_TSGLOBAL_TABLE_CURRENT_TSGLOBAL_TABLE_START_TV"

var _GlobalVar_index = [...]uint8{0, 21, 45, 66, 89, 110}

func (i GlobalVar) String() string {
	if i >= GlobalVar(len(_GlobalVar_index)-1) {
		return "GlobalVar(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GlobalVar_name[_GlobalVar_index[i]:_GlobalVar_index[i+1]]
}
