// Code generated by "stringer -type=Operation"; DO NOT EDIT.

package tcp_estats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OPERATION_SET-0]
	_ = x[OPERATION_ADD-1]
	_ = x[OPERATION_SUB-2]
	_ = x[OPERATION_MAX-3]
	_ = x[OPERATION_MIN-4]
}

const _Operation_name = "OPERATION_SETOPERATION_ADDOPERATION_SUBOPERATION_MAXOPERATION_MIN"

var _Operation_index = [...]uint8{0, 13, 26, 39, 52, 65}

func (i Operation) String() string {
	if i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
